# Generated by Django 3.0.7 on 2021-02-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry_code',
            field=models.CharField(blank=True, help_text='업종코드', max_length=50, null=True),
        ),
    ]
